# MNIST works only with MLP and LeNet :(
# CIFAR works with resnet18

device: "cuda"          # "cuda" or "cpu"
dataset: "MNIST"      # "MNIST", "CIFAR10", "CIFAR100"
batch_size: 64
model: "MLP"       # "resnet18", "MLP", "LeNet"
optimizer: "SGD"        # "SGD", "Adam", "AdamW", etc.
learning_rate: 0.001
momentum: 0.9
weight_decay: 0.0005
scheduler: "StepLR"     # "StepLR", "ReduceLROnPlateau", None
early_stopping: true
epochs: 10

step_size: 30
gamma: 0.1
factor: 0.1
patience: 10